import { expect, test } from '@playwright/test'
import { BASE, seedModel, seedProvider, signUpFresh } from './helpers/auth'
for (const width of [1440, 390, 320]) {
 test(`Thiết kế nhân vật: biến thể, bản chính và reload ở ${width}px`, async ({page}) => {
  await page.setViewportSize({width,height:900});await signUpFresh(page)
  const provider=await seedProvider(page)
  const chat=await seedModel(page,provider,{modelId:'mock-chat-model',displayName:'Chat',kind:'llm'})
  await seedModel(page,provider,{modelId:'mock-image-model',displayName:'Image',kind:'image'})
  const created=await page.request.post(BASE+'/api/plans',{data:{kind:'planner'}})
  const {session}=await created.json()
  const models=(await (await page.request.get(BASE+'/api/models')).json()).models
  await page.request.patch(BASE+`/api/plans/${session.id}/setup`,{data:{chatModelId:models.find((m:any)=>m.kind==='llm').id,imageModelId:models.find((m:any)=>m.kind==='image').id}})
  await page.request.put(BASE+`/api/plans/${session.id}/cast`,{data:{cast:[{id:'lan',name:'Lan',role:'Nhân vật chính',appearance:'Áo đỏ',voice:{},storage:'project'}]}})
  await page.goto(BASE+`/?page=planner-characters&session=${session.id}`)
  await expect(page.getByRole('heading',{name:'Thiết kế nhân vật',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'AI điền hồ sơ từ mô tả',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'Màu da',exact:true})).toHaveValue('Da nâu sáng')
  await expect(page.getByRole('textbox',{name:'Chiều cao (cm)',exact:true})).toHaveValue('172')
  await page.locator('.pc-proposals').getByRole('button',{name:/AI/}).click()
  await expect(page.locator('.pc-variant')).toHaveCount(4)
  await expect(page.locator('.pc-variant img')).toHaveCount(0)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button',{name:'Tạo ảnh hàng loạt các phương án',exact:true}).click()
  await expect(page.locator('.pc-variant img')).toHaveCount(4, {timeout:30000})
  await expect(page.getByRole('button',{name:'Tạo ảnh hàng loạt các phương án',exact:true})).toBeDisabled()
  await page.locator('.pc-variant').nth(1).click()
  await expect(page.getByRole('textbox',{name:'Màu da',exact:true})).not.toBeEmpty()
  await page.getByRole('textbox',{name:'Chiều cao (cm)',exact:true}).fill('175')
  await page.locator('.pc-save-bar').getByRole('button',{name:'Lưu thay đổi',exact:true}).click()
  await page.getByRole('button',{name:'Dùng phương án này',exact:true}).click()
  await expect(page.locator('.pc-variant').nth(1).locator('.pc-selected')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('textbox',{name:'Chiều cao (cm)',exact:true})).toHaveValue('175')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('textbox',{name:'Màu da',exact:true}).fill('Da nâu ấm')
  await page.getByRole('button',{name:'Về trò chuyện',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('dialog').getByRole('button',{name:'Huỷ',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'Màu da',exact:true})).toHaveValue('Da nâu ấm')
  if (width <= 760) await page.getByRole('button',{name:'Mở menu',exact:true}).click()
  await page.getByRole('button',{name:'Tạo kịch bản AI',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('dialog').getByRole('button',{name:'Bỏ thay đổi',exact:true}).click()
  await expect(page.locator('.plan-chat')).toBeVisible()
  await expect(page).toHaveURL(new RegExp(`page=planner&session=${session.id}`))
  await page.goBack()
  await expect(page.getByRole('heading',{name:'Thiết kế nhân vật',exact:true})).toBeVisible()
  await expect(page.getByRole('textbox',{name:'Chiều cao (cm)',exact:true})).toHaveValue('175')
 })
}
