import type { Database } from '../db/index'
import { ownedProject } from './service'
import { badRequest, notFound } from '../lib/errors'
import type { LocationReference } from '../planner/artifacts'
import { MAX_LOCATIONS } from '../planner/artifacts'
import { assertLocationUpload, normalizeLocation, transaction, type LocationInput } from '../planner/locations'
export function listProjectLocations(db:Database,userId:string,projectId:string):LocationReference[]{ownedProject(db,userId,projectId);return (db.prepare('SELECT * FROM project_locations WHERE project_id = ? ORDER BY created_at, id').all(projectId) as any[]).map(row=>({id:row.id,name:row.name,stage:row.stage,description:row.description,continuityNotes:row.continuity_notes,imagePrompt:row.image_prompt,reference:row.reference_upload_id?{uploadId:row.reference_upload_id}:null,revision:row.revision}))}
export function ownedProjectLocation(db:Database,userId:string,projectId:string,id:string):LocationReference{const item=listProjectLocations(db,userId,projectId).find(x=>x.id===id);if(!item)throw notFound('Không tìm thấy bối cảnh');return item}
export function saveProjectLocation(db:Database,userId:string,projectId:string,input:LocationInput,id?:string):LocationReference{return transaction(db,()=>{const all=listProjectLocations(db,userId,projectId);const old=id?ownedProjectLocation(db,userId,projectId,id):undefined;if(!old&&all.length>=MAX_LOCATIONS)throw badRequest('Tối đa 20 bối cảnh');const item=normalizeLocation(input,old);if(item.reference)assertLocationUpload(db,userId,item.reference.uploadId);if(old)db.prepare('UPDATE project_locations SET name=?,stage=?,description=?,continuity_notes=?,image_prompt=?,reference_upload_id=?,revision=?,updated_at=? WHERE id=? AND project_id=?').run(item.name,item.stage,item.description,item.continuityNotes,item.imagePrompt,item.reference?.uploadId??null,item.revision,Date.now(),item.id,projectId);else db.prepare('INSERT INTO project_locations(id,project_id,name,stage,description,continuity_notes,image_prompt,reference_upload_id,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(item.id,projectId,item.name,item.stage,item.description,item.continuityNotes,item.imagePrompt,item.reference?.uploadId??null,item.revision,Date.now(),Date.now());return item})}
export function removeProjectLocation(db:Database,userId:string,projectId:string,id:string):void{transaction(db,()=>{ownedProjectLocation(db,userId,projectId,id);db.prepare('UPDATE scenes SET location_id=NULL, updated_at=? WHERE project_id=? AND location_id=?').run(Date.now(),projectId,id);db.prepare('DELETE FROM project_locations WHERE id=? AND project_id=?').run(id,projectId)})}
export function assignProjectLocation(db:Database,userId:string,projectId:string,locationId:string|null,sceneIds:string[]):void{transaction(db,()=>{ownedProject(db,userId,projectId);if(locationId)ownedProjectLocation(db,userId,projectId,locationId);if(new Set(sceneIds).size!==sceneIds.length)throw badRequest('Cảnh không hợp lệ');for(const id of sceneIds){if(!db.prepare('SELECT id FROM scenes WHERE id=? AND project_id=?').get(id,projectId))throw notFound('Không tìm thấy cảnh');}for(const id of sceneIds)db.prepare('UPDATE scenes SET location_id=?,updated_at=? WHERE id=? AND project_id=?').run(locationId,Date.now(),id,projectId)})}
