import express,{Router} from 'express'
import { randomUUID } from 'node:crypto'
import { z } from 'zod'
import type { Database } from '../db/index'
import type { AppEnv } from '../env'
import type { MediaStore } from '../media/store'
import type { Worker } from '../generations/worker'
import { requireUser } from '../auth/middleware'
import { badRequest,validationError } from '../lib/errors'
import { enqueueGeneration } from '../generations/enqueue'
import { adoptGenerationImage,saveSessionUpload } from '../planner/storyboard'
import { locationInputSchema,locationReferencePrompt } from '../planner/locations'
import { listProjectLocations,ownedProjectLocation,saveProjectLocation,removeProjectLocation,assignProjectLocation } from './locations'
export function projectLocationRoutes(db:Database,env:AppEnv,mediaStore:MediaStore,worker:Worker):Router {const router=Router();const deps={db,env,mediaStore};const raw=express.raw({type:['image/*','application/octet-stream'],limit:env.MAX_REFERENCE_BYTES});const reply=(userId:string,id:string)=>({locations:listProjectLocations(db,userId,id)});router.get('/:id/locations',(req,res)=>{const user=requireUser(req);res.json(reply(user.id,req.params.id))});
router.post('/:id/locations',(req,res)=>{const user=requireUser(req);const parsed=locationInputSchema.safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);const location=saveProjectLocation(db,user.id,req.params.id,parsed.data);res.status(201).json({location,...reply(user.id,req.params.id)})});
const saveAll=(db:Database,userId:string,projectId:string,items:z.infer<typeof locationInputSchema>[])=>{const existing=listProjectLocations(db,userId,projectId);const keep=new Set(items.map(item=>item.id).filter(Boolean) as string[]);for(const old of existing)if(!keep.has(old.id))removeProjectLocation(db,userId,projectId,old.id);const saved=items.map(item=>saveProjectLocation(db,userId,projectId,item,item.id&&existing.some(old=>old.id===item.id)?item.id:undefined));return saved};
router.put('/:id/locations',(req,res)=>{const user=requireUser(req);const parsed=z.object({locations:z.array(locationInputSchema).max(20)}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);res.json({locations:saveAll(db,user.id,req.params.id,parsed.data.locations)})});
router.post('/:id/locations/assign',(req,res)=>{const user=requireUser(req);const parsed=z.object({locationId:z.string().nullable(),sceneIds:z.array(z.string()).max(30)}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);assignProjectLocation(db,user.id,req.params.id,parsed.data.locationId,parsed.data.sceneIds);res.json(reply(user.id,req.params.id))});
router.post('/:id/locations/:locationId/reference/generate',(req,res)=>{const user=requireUser(req);const location=ownedProjectLocation(db,user.id,req.params.id,req.params.locationId);const parsed=z.object({modelId:z.string().min(1)}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);const generation=enqueueGeneration({db,env,worker,userId:user.id,request:{data:{projectId:req.params.id,modelId:parsed.data.modelId,prompt:locationReferencePrompt(location),params:{size:'1536x1024'},idempotencyKey:`location-${randomUUID()}`},scene:null}}).generation;res.status(202).json({generation,locationId:location.id,revision:location.revision})});
router.patch('/:id/locations/:locationId',(req,res)=>{const user=requireUser(req);const old=ownedProjectLocation(db,user.id,req.params.id,req.params.locationId);const parsed=locationInputSchema.partial().safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);const location=saveProjectLocation(db,user.id,req.params.id,{...old,...parsed.data},old.id);res.json({location,...reply(user.id,req.params.id)})});
router.delete('/:id/locations/:locationId',(req,res)=>{const user=requireUser(req);removeProjectLocation(db,user.id,req.params.id,req.params.locationId);res.json(reply(user.id,req.params.id))});
router.post('/:id/locations/:locationId/reference',(req,res)=>{const user=requireUser(req);const location=ownedProjectLocation(db,user.id,req.params.id,req.params.locationId);const parsed=z.object({modelId:z.string()}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);const generation=enqueueGeneration({db,env,worker,userId:user.id,request:{data:{projectId:req.params.id,modelId:parsed.data.modelId,prompt:locationReferencePrompt(location),params:{size:'1536x1024'},idempotencyKey:`location-${randomUUID()}`},scene:null}}).generation;res.status(202).json({generation,locationId:location.id,revision:location.revision})});
router.post('/:id/locations/:locationId/reference/upload',raw,(req,res)=>{const user=requireUser(req);const location=ownedProjectLocation(db,user.id,req.params.id,req.params.locationId);if(!Buffer.isBuffer(req.body))throw badRequest('Ảnh không hợp lệ');const uploadId=saveSessionUpload(deps,user.id,req.body);saveProjectLocation(db,user.id,req.params.id,{...location,reference:{uploadId}},location.id);res.json(reply(user.id,req.params.id))});
router.post('/:id/locations/:locationId/reference/attach',(req,res)=>{const user=requireUser(req);const location=ownedProjectLocation(db,user.id,req.params.id,req.params.locationId);const parsed=z.object({generationId:z.string(),assetId:z.string().optional(),revision:z.number().int().optional()}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);if(parsed.data.revision!==undefined&&parsed.data.revision!==location.revision)throw badRequest('Bối cảnh đã thay đổi. Hãy kiểm tra ảnh trước khi gắn.');const uploadId=adoptGenerationImage(deps,user.id,parsed.data.generationId,parsed.data.assetId);saveProjectLocation(db,user.id,req.params.id,{...location,reference:{uploadId}},location.id);res.json(reply(user.id,req.params.id))});
router.delete('/:id/locations/:locationId/reference',(req,res)=>{const user=requireUser(req);const location=ownedProjectLocation(db,user.id,req.params.id,req.params.locationId);saveProjectLocation(db,user.id,req.params.id,{...location,reference:null},location.id);res.json(reply(user.id,req.params.id))});return router}
