import express, { Router } from 'express'
import { randomUUID } from 'node:crypto'
import { z } from 'zod'
import type { Database } from '../db/index'
import type { AppEnv } from '../env'
import type { MediaStore } from '../media/store'
import type { Worker } from '../generations/worker'
import { enqueueGeneration } from '../generations/enqueue'
import { requireUser } from '../auth/middleware'
import { badRequest, validationError } from '../lib/errors'
import { saveSessionUpload, adoptGenerationImage } from './storyboard'
import { ownedSession } from './service'
import { chatText, parseJsonLoose } from '../llm/chat'
import { resolveLlmTarget } from '../llm/connections'
import { locationInputSchema, listPlanLocations, savePlanLocations, updatePlanLocation, removePlanLocation, ownedPlanLocation, assignPlanLocation, locationReferencePrompt, planLocationSession } from './locations'

export function planLocationRoutes(db:Database,env:AppEnv,mediaStore:MediaStore,worker:Worker):Router {
 const router=Router();const deps={db,env,mediaStore};const raw=express.raw({type:['image/*','application/octet-stream'],limit:env.MAX_REFERENCE_BYTES});
 const reply=(userId:string,id:string)=>({locations:listPlanLocations(db,userId,id),session:planLocationSession(db,userId,id)});
 router.get('/:id/locations',(req,res)=>{const user=requireUser(req);res.json(reply(user.id,req.params.id))});
 router.put('/:id/locations',(req,res)=>{const user=requireUser(req);const parsed=z.object({locations:z.array(locationInputSchema).max(20)}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);savePlanLocations(db,user.id,req.params.id,parsed.data.locations);res.json(reply(user.id,req.params.id))});
 router.post('/:id/locations',(req,res)=>{const user=requireUser(req);const parsed=locationInputSchema.safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);savePlanLocations(db,user.id,req.params.id,[...listPlanLocations(db,user.id,req.params.id),parsed.data]);res.status(201).json(reply(user.id,req.params.id))});
 router.post('/:id/locations/propose',async(req,res)=>{const user=requireUser(req);const session=ownedSession(db,user.id,req.params.id);const target=resolveLlmTarget(db,env,user.id,session.chat_model_id??undefined);const rawText=await chatText(env,target,[{role:'system',content:'Suggest up to 20 recurring filming locations as JSON {locations:[{name,stage,description,continuityNotes,imagePrompt}]}. Empty environment only, no people. This is a suggestion, do not modify existing locations.'},{role:'user',content:JSON.stringify({script:session.script_json,existing:listPlanLocations(db,user.id,session.id)})}]);const result=parseJsonLoose(rawText) as {locations?:unknown}|null;const parsed=z.array(locationInputSchema.omit({id:true,reference:true})).max(20).safeParse(result?.locations);if(!parsed.success)throw badRequest('AI không trả về bối cảnh hợp lệ');res.json({...reply(user.id,session.id),locations:[...listPlanLocations(db,user.id,session.id),...parsed.data.map(item=>({...item,id:randomUUID(),reference:null,revision:1}))],suggestions:parsed.data})});
 router.post('/:id/locations/assign',(req,res)=>{const user=requireUser(req);const parsed=z.object({locationId:z.string().nullable(),frameIds:z.array(z.string()).max(30)}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);assignPlanLocation(db,user.id,req.params.id,parsed.data.locationId,parsed.data.frameIds);res.json(reply(user.id,req.params.id))});
 router.patch('/:id/locations/:locationId',(req,res)=>{const user=requireUser(req);const parsed=locationInputSchema.partial().safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);updatePlanLocation(db,user.id,req.params.id,req.params.locationId,parsed.data);res.json(reply(user.id,req.params.id))});
 router.delete('/:id/locations/:locationId',(req,res)=>{const user=requireUser(req);removePlanLocation(db,user.id,req.params.id,req.params.locationId);res.json(reply(user.id,req.params.id))});
 router.post('/:id/locations/:locationId/reference',(req,res)=>{const user=requireUser(req);const session=ownedSession(db,user.id,req.params.id);const location=ownedPlanLocation(db,user.id,session.id,req.params.locationId);if(!session.image_model_id)throw badRequest('Chưa chọn model ảnh');const generation=enqueueGeneration({db,env,worker,userId:user.id,request:{data:{modelId:session.image_model_id,prompt:locationReferencePrompt(location),params:{size:'1536x1024'},idempotencyKey:`location-${randomUUID()}`},scene:null}}).generation;res.status(202).json({generation,locationId:location.id,revision:location.revision})});
 router.post('/:id/locations/:locationId/reference/generate',(req,res)=>{const user=requireUser(req);const session=ownedSession(db,user.id,req.params.id);const location=ownedPlanLocation(db,user.id,session.id,req.params.locationId);const parsed=z.object({modelId:z.string().min(1).optional()}).safeParse(req.body??{});if(!parsed.success)throw validationError(parsed.error);const modelId=parsed.data.modelId??session.image_model_id;if(!modelId)throw badRequest('Chưa chọn model ảnh');const generation=enqueueGeneration({db,env,worker,userId:user.id,request:{data:{modelId,prompt:locationReferencePrompt(location),params:{size:'1536x1024'},idempotencyKey:`location-${randomUUID()}`},scene:null}}).generation;res.status(202).json({generation,locationId:location.id,revision:location.revision})});
 router.post('/:id/locations/:locationId/reference/upload',raw,(req,res)=>{const user=requireUser(req);ownedPlanLocation(db,user.id,req.params.id,req.params.locationId);if(!Buffer.isBuffer(req.body))throw badRequest('Ảnh không hợp lệ');const uploadId=saveSessionUpload(deps,user.id,req.body);updatePlanLocation(db,user.id,req.params.id,req.params.locationId,{reference:{uploadId}});res.json(reply(user.id,req.params.id))});
 router.post('/:id/locations/:locationId/reference/attach',(req,res)=>{const user=requireUser(req);const location=ownedPlanLocation(db,user.id,req.params.id,req.params.locationId);const parsed=z.object({generationId:z.string(),assetId:z.string().optional(),revision:z.number().int().optional()}).safeParse(req.body);if(!parsed.success)throw validationError(parsed.error);if(parsed.data.revision!==undefined&&parsed.data.revision!==location.revision)throw badRequest('Bối cảnh đã thay đổi. Hãy kiểm tra ảnh trước khi gắn.');const uploadId=adoptGenerationImage(deps,user.id,parsed.data.generationId,parsed.data.assetId);updatePlanLocation(db,user.id,req.params.id,location.id,{reference:{uploadId}});res.json(reply(user.id,req.params.id))});
 router.delete('/:id/locations/:locationId/reference',(req,res)=>{const user=requireUser(req);updatePlanLocation(db,user.id,req.params.id,req.params.locationId,{reference:null});res.json(reply(user.id,req.params.id))});return router
}
